# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Set node version env var
      run: echo ::set-env name=NODE_VERSION::$(node --version)

    - uses: actions/cache@v1
      id: cache-dependencies
      with:
        # intentionally cache node_modules instead of yarn cache
        path: node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}-${{ env.NODE_VERSION }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Install
      if: steps.cache-dependencies.outputs.cache-hit != 'true'
      run: yarn --frozen-lockfile

    - name: Build
      run: yarn build

    # Runs a set of commands using the runners shell
    - name: Lint
      run: yarn lint

    - name: Test
      run: yarn test

    - name: Report bundle size
      env:
        BUNDLEWATCH_GITHUB_TOKEN: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}
      run: yarn bundlewatch

    - name: Create analyze bundle size page
      run: yarn analyze --html bundle-stats.html
    - uses: actions/upload-artifact@v1
      with:
        name: bundle-stats
        path: bundle-stats.html
